volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    image: rum6/kittygram_backend:latest
    env_file:
      - .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  frontend:
    image: rum6/kittygram_frontend:latest
    env_file:
      - .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  gateway:
    image: rum6/kittygram_gateway:latest
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - backend
      - frontend